CREATE TABLE role (
                      id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code    VARCHAR(30)  NOT NULL UNIQUE,
                      libelle VARCHAR(100) NOT NULL
);

CREATE TABLE permission (
                            id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code    VARCHAR(50)  NOT NULL UNIQUE,
                            libelle VARCHAR(150) NOT NULL
);

CREATE TABLE role_permission (
                                 role_id       BIGINT NOT NULL REFERENCES role(id),
                                 permission_id BIGINT NOT NULL REFERENCES permission(id),
                                 PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE utilisateur (
                             id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             email               VARCHAR(150) NOT NULL UNIQUE,
                             mot_de_passe_hash   VARCHAR(100) NOT NULL,
                             nom                 VARCHAR(100),
                             prenom              VARCHAR(100),
                             pays                VARCHAR(20),               -- code pays, ou NULL = tous (super admin)
                             actif               BOOLEAN NOT NULL DEFAULT TRUE,
                             date_creation       TIMESTAMP NOT NULL DEFAULT now(),
                             derniere_connexion  TIMESTAMP,
                             tentatives_echouees INT NOT NULL DEFAULT 0,
                             verrouille_jusqu_a  TIMESTAMP
);

CREATE TABLE utilisateur_role (
                                  utilisateur_id BIGINT NOT NULL REFERENCES utilisateur(id),
                                  role_id        BIGINT NOT NULL REFERENCES role(id),
                                  PRIMARY KEY (utilisateur_id, role_id)
);

CREATE TABLE refresh_token (
                               id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               utilisateur_id BIGINT NOT NULL REFERENCES utilisateur(id),
                               token_hash     VARCHAR(200) NOT NULL,
                               expire_at      TIMESTAMP NOT NULL,
                               revoque        BOOLEAN NOT NULL DEFAULT FALSE,
                               cree_at        TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE journal_audit (
                               id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               utilisateur_id BIGINT,
                               action         VARCHAR(100) NOT NULL,
                               ressource      VARCHAR(150),
                               pays_cible     VARCHAR(20),
                               horodatage     TIMESTAMP NOT NULL DEFAULT now(),
                               ip             VARCHAR(45),
                               resultat       VARCHAR(20)
);

CREATE INDEX idx_utilisateur_pays ON utilisateur(pays);
CREATE INDEX idx_audit_horodatage ON journal_audit(horodatage);