CREATE TABLE exploitation (
                              id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nom  VARCHAR(150) NOT NULL,
                              pays VARCHAR(50)  NOT NULL
);

CREATE TABLE entrepot (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nom             VARCHAR(150) NOT NULL,
                          localisation    VARCHAR(255),
                          exploitation_id BIGINT NOT NULL REFERENCES exploitation(id)
);

CREATE TABLE capteur (
                         id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         identifiant_mqtt VARCHAR(100) NOT NULL UNIQUE,
                         entrepot_id      BIGINT NOT NULL REFERENCES entrepot(id)
);

CREATE TABLE lot (
                     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     reference                VARCHAR(100) NOT NULL UNIQUE,
                     exploitation_id          BIGINT NOT NULL REFERENCES exploitation(id),
                     entrepot_id              BIGINT NOT NULL REFERENCES entrepot(id),
                     date_stockage            TIMESTAMP NOT NULL,
                     statut                   VARCHAR(20) NOT NULL CHECK (statut IN ('CONFORME','EN_ALERTE','PERIME')),
                     caracteristiques_qualite VARCHAR(500)
);

CREATE TABLE mesure (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        entrepot_id BIGINT NOT NULL REFERENCES entrepot(id),
                        capteur_id  BIGINT REFERENCES capteur(id),
                        temperature NUMERIC(5,2) NOT NULL,
                        humidite    NUMERIC(5,2) NOT NULL,
                        mesure_at   TIMESTAMP NOT NULL
);
CREATE INDEX idx_mesure_entrepot_ts ON mesure (entrepot_id, mesure_at);

CREATE TABLE alerte (
                        id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        type               VARCHAR(20) NOT NULL CHECK (type IN ('CONDITION','PEREMPTION')),
                        statut             VARCHAR(20) NOT NULL CHECK (statut IN ('ACTIVE','RESOLUE')),
                        entrepot_id        BIGINT REFERENCES entrepot(id),
                        lot_id             BIGINT REFERENCES lot(id),
                        message            VARCHAR(500),
                        valeur_temperature NUMERIC(5,2),
                        valeur_humidite    NUMERIC(5,2),
                        declenchee_at      TIMESTAMP NOT NULL,
                        email_envoye       BOOLEAN NOT NULL DEFAULT FALSE,
                        resolue_at         TIMESTAMP
);
CREATE INDEX idx_alerte_statut ON alerte (statut);